services:
  db:
    image: postgres:18.1-alpine
    hostname: db
    env_file: 
      - .env 
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      matchup-network:
        ipv4_address: 172.71.0.5

  redis:
    image: valkey/valkey:8-alpine
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "PING"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      matchup-network:
        ipv4_address: 172.71.0.6

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - .env
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - matchup-network

  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      matchup-network:
        ipv4_address: 172.71.0.7

  api:
    build:
      context: .
      args:
        SERVICE_NAME: api
    env_file:
      - .env
    environment:
      DB_SSL_MODE: disable
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 100ms
      retries: 3
      start_period: 10s
    networks:
      matchup-network:
        ipv4_address: 172.71.0.10

  # cron:
  #   build:
  #     context: .
  #     args:
  #       SERVICE_NAME: cron
  #       ARCHITECTURE: amd64
  #   env_file: 
  #     - .env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     migrate:
  #       condition: service_completed_successfully
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8000/health"]
  #     interval: 30s
  #     timeout: 100ms
  #     retries: 3
  #     start_period: 10s
  #   networks:
  #     - matchup-network

  web:
    image: nginx:1.27-alpine
    user: root
    volumes:
      - ./services/frontend/build:/usr/share/nginx/html:ro
      - ./services/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
    #   api:
    #     condition: service_healthy
    restart: on-failure
    networks:
      matchup-network:
        ipv4_address: 172.71.0.15

volumes:
  postgres_data:
    driver: local
  valkey_data:
    driver: local
  minio_data:
    driver: local
  minio_config:
    driver: local

networks:
  matchup-network:
    driver: bridge 
    ipam:
      driver: default
      config:
        - subnet: 172.71.0.0/24
