package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/Gooowan/matchup/modules/core/types"
)

// ANSI color codes
var (
	ColorReset  = "\033[0m"
	ColorRed    = "\033[31m"
	ColorGreen  = "\033[32m"
	ColorYellow = "\033[33m"
	ColorBlue   = "\033[34m"
	ColorPurple = "\033[35m"
	ColorCyan   = "\033[36m"
	ColorWhite  = "\033[37m"
	ColorBold   = "\033[1m"
)

func init() {
	// Disable colors if NO_COLOR env var is set or if we're in certain CI environments
	// that don't handle ANSI colors well
	if os.Getenv("NO_COLOR") != "" || os.Getenv("TERM") == "dumb" {
		ColorReset = ""
		ColorRed = ""
		ColorGreen = ""
		ColorYellow = ""
		ColorBlue = ""
		ColorPurple = ""
		ColorCyan = ""
		ColorWhite = ""
		ColorBold = ""
	}
}

// Logging helpers
func logInfo(format string, args ...interface{}) {
	fmt.Printf(ColorBlue+"[INFO]"+ColorReset+" "+format+"\n", args...)
}

func logSuccess(format string, args ...interface{}) {
	fmt.Printf(ColorGreen+"[SUCCESS]"+ColorReset+" "+format+"\n", args...)
}

func logWarning(format string, args ...interface{}) {
	fmt.Printf(ColorYellow+"[WARNING]"+ColorReset+" "+format+"\n", args...)
}

func logError(format string, args ...interface{}) {
	fmt.Printf(ColorRed+"[ERROR]"+ColorReset+" "+format+"\n", args...)
}

func logHeader(text string) {
	fmt.Printf("\n"+ColorBold+ColorCyan+"=== %s ==="+ColorReset+"\n", text)
}

func logStep(format string, args ...interface{}) {
	fmt.Printf(ColorPurple+"→"+ColorReset+" "+format+"\n", args...)
}

func main() {
	var (
		configPath = flag.String("config", "config.yaml", "Config file path")
		moduleDirs = flag.String("module-dirs", "modules,shared", "Comma-separated list of module directories")
		outputPath = flag.String("output", "build/combined_schema.sql", "Schema output path")
		schemaOnly = flag.Bool("schema-only", false, "Generate only, without running SQLC. Puts views into separate file.")
	)
	flag.Parse()

	dirs := strings.Split(*moduleDirs, ",")
	for i, dir := range dirs {
		dirs[i] = strings.TrimSpace(dir)
	}

	logHeader("SCHEMA GENERATOR")
	logInfo("Config file: %s", *configPath)
	logInfo("Module directories: %s", *moduleDirs)
	logInfo("Output path: %s", *outputPath)
	if *schemaOnly {
		logInfo("Mode: Schema only (SQLC generation disabled)")
	} else {
		logInfo("Mode: Full generation (schema + SQLC)")
	}

	var config types.Config
	yamlFile, err := os.ReadFile(*configPath)
	if err != nil {
		logError("Failed to read config file %s: %v", *configPath, err)
		os.Exit(1)
	}

	if err := yaml.Unmarshal(yamlFile, &config); err != nil {
		logError("Failed to unmarshal config: %v", err)
		os.Exit(1)
	}

	logSuccess("Configuration loaded successfully")
	logInfo("Found %d modules in config: %v", len(config.Modules), config.Modules)

	if err := buildSchema(config, *outputPath, dirs, *schemaOnly); err != nil {
		logError("Failed to build schema: %v", err)
		os.Exit(1)
	}

	if !*schemaOnly {
		if err := generateSQLC(config, dirs); err != nil {
			logError("Failed to generate SQLC: %v", err)
			os.Exit(1)
		}
	} else {
		logInfo("Skipping SQLC generation (--schema-only flag enabled)")
	}

	logHeader("COMPLETED")
	if *schemaOnly {
		logSuccess("Schema-only generation completed successfully!")
	} else {
		logSuccess("Full generation completed successfully!")
	}
}

func buildSchema(config types.Config, outputPath string, moduleDirs []string, schemaOnly bool) error {
	logHeader("BUILDING SCHEMA")

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	var combinedSchema strings.Builder
	combinedSchema.WriteString("-- Generated by schema-gen command. DO NOT EDIT.\n")
	combinedSchema.WriteString("-- Combined schema from all modules\n\n")

	var combinedViews strings.Builder
	if schemaOnly {
		combinedViews.WriteString("-- Generated by schema-gen command. DO NOT EDIT.\n")
		combinedViews.WriteString("-- Combined views from all modules\n\n")
	}

	hasSchema := false
	hasViews := false
	processedCount := 0
	viewsProcessedCount := 0

	for _, moduleName := range config.Modules {
		moduleName = strings.TrimSpace(moduleName)
		if moduleName == "" {
			continue
		}

		modulePath, err := findModuleInDirs(moduleName, moduleDirs)
		if err != nil {
			logWarning("Module not found: %v", err)
			continue
		}

		schemaPath := filepath.Join(modulePath, "schema.sql")
		if _, err := os.Stat(schemaPath); os.IsNotExist(err) {
			logStep("Skipping %s (no schema.sql)", moduleName)
			continue
		}

		logStep("Processing schema: %s", schemaPath)
		hasSchema = true
		processedCount++

		content, err := os.ReadFile(schemaPath)
		if err != nil {
			return fmt.Errorf("failed to read %s: %w", schemaPath, err)
		}

		combinedSchema.WriteString(fmt.Sprintf("-- Module: %s\n", modulePath))
		combinedSchema.WriteString(string(content))
		combinedSchema.WriteString("\n\n")

		// Process views.sql
		viewsPath := filepath.Join(modulePath, "views.sql")
		if _, err := os.Stat(viewsPath); err == nil {
			logStep("Processing views: %s", viewsPath)
			hasViews = true
			viewsProcessedCount++

			viewsContent, err := os.ReadFile(viewsPath)
			if err != nil {
				return fmt.Errorf("failed to read %s: %w", viewsPath, err)
			}

			if schemaOnly {
				// In schema-only mode, write views to separate file
				combinedViews.WriteString(fmt.Sprintf("-- Views for module: %s\n", modulePath))
				combinedViews.WriteString(string(viewsContent))
				combinedViews.WriteString("\n\n")
			} else {
				// In normal mode, include views in combined schema
				combinedSchema.WriteString(fmt.Sprintf("-- Views for module: %s\n", modulePath))
				combinedSchema.WriteString(string(viewsContent))
				combinedSchema.WriteString("\n\n")
			}
		}
	}

	if !hasSchema {
		logWarning("No modules with schema.sql found, skipping schema build")
		return nil
	}

	if err := os.WriteFile(outputPath, []byte(combinedSchema.String()), 0644); err != nil {
		return fmt.Errorf("failed to write combined schema: %w", err)
	}

	logSuccess("Combined schema written to %s", outputPath)
	logInfo("Processed %d schema files", processedCount)

	// Write views to separate file if in schema-only mode
	if schemaOnly && hasViews {
		viewsOutputPath := filepath.Join(filepath.Dir(outputPath), "combined_views.sql")
		if err := os.WriteFile(viewsOutputPath, []byte(combinedViews.String()), 0644); err != nil {
			return fmt.Errorf("failed to write combined views: %w", err)
		}
		logSuccess("Combined views written to %s", viewsOutputPath)
		logInfo("Processed %d views files", viewsProcessedCount)
	}

	return nil
}

func generateSQLC(config types.Config, moduleDirs []string) error {
	logHeader("GENERATING SQLC")

	hasSQLC := false
	processedCount := 0

	for _, moduleName := range config.Modules {
		moduleName = strings.TrimSpace(moduleName)
		if moduleName == "" {
			continue
		}

		modulePath, err := findModuleInDirs(moduleName, moduleDirs)
		if err != nil {
			logWarning("Module not found: %v", err)
			continue
		}

		sqlcConfigPath := filepath.Join(modulePath, "sqlc.yaml")
		if _, err := os.Stat(sqlcConfigPath); os.IsNotExist(err) {
			logStep("Skipping %s (no sqlc.yaml)", moduleName)
			continue
		}

		logStep("Generating SQLC for module: %s", modulePath)
		hasSQLC = true
		processedCount++

		cmd := exec.Command("sqlc", "generate")
		cmd.Dir = modulePath
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr

		if err := cmd.Run(); err != nil {
			return fmt.Errorf("failed to generate SQLC for %s: %w", modulePath, err)
		}

		logSuccess("SQLC generation completed for %s", moduleName)
	}

	if !hasSQLC {
		logWarning("No modules with sqlc.yaml found, skipping SQLC generation")
	} else {
		logInfo("Processed %d SQLC modules", processedCount)
	}

	return nil
}

func findModuleInDirs(moduleName string, dirs []string) (string, error) {
	for _, dir := range dirs {
		modulePath := filepath.Join(dir, moduleName)
		if _, err := os.Stat(modulePath); err == nil {
			return modulePath, nil
		}
	}
	return "", fmt.Errorf("module %s not found in any of the directories: %v", moduleName, dirs)
}
